export const practiceAreas = [
"Alternative Dispute Resolution Practices.",
"Aviation",
"Banking And Finance",
"Business Establishment and corporate Immigration",
"Capital markets",
"Company secretarial services",
"Compliance and Investigation",
"Corporate Advisory",
"Corporate Governance",
"Employment",
"Energy and natural resources",
"Entertainments",
"Human Rights",
"International trade",
"Intellectual property",
"Litigation",
"civil and criminal",
"Mergers, acquisitions and restructuring",
"Telecommunications, media and Technology",
"Information Technology",
"Oil and Gas",
"Power",
"Probono",
"Public policy and regulations",
"Real Estate and Property Management",
"Shipping, maritime Legal Advisory",
"Tax",
"Startup Funding",
]